import { supabase } from "./supabase";

export const SQL_SETUP_SCRIPT = `-- SQL setup script for Supabase
CREATE TABLE IF NOT EXISTS roster_cham_cong (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  l07 TEXT,
  business TEXT,
  ma_nv TEXT,
  full_name TEXT,
  ngay TEXT,
  type TEXT,
  class TEXT,
  gio_vao TEXT,
  gio_ra TEXT,
  duration NUMERIC,
  notes TEXT,
  charge_to_center_mkt TEXT,
  unique_id TEXT UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure column exists if table was already created
DO $$ 
BEGIN 
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='roster_cham_cong' AND column_name='charge_to_center_mkt') THEN
    ALTER TABLE roster_cham_cong ADD COLUMN charge_to_center_mkt TEXT;
  END IF;
END $$;

-- Row Level Security (RLS) - Allow ALL operations for anon role
ALTER TABLE roster_cham_cong ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for anon" ON roster_cham_cong FOR ALL USING (true) WITH CHECK (true);
`;

export async function syncRosterToSupabase(
  rosterData: Record<string, unknown>[],
  onProgress: (successCount: number, total: number) => void
) {
  const chunkSize = 200; // Reduced from 1000 to avoid payload size/timeout issues
  let successCount = 0;

  // Helper to get value from object with multiple possible keys (case-insensitive)
  const getVal = (obj: Record<string, unknown>, keys: string[]) => {
    if (!obj) return "";
    for (const k of keys) {
      if (obj[k] !== undefined && obj[k] !== null && obj[k] !== "") return obj[k] as string | number;
    }
    // Case-insensitive search
    const objKeys = Object.keys(obj);
    for (const k of keys) {
      const target = k.toLowerCase();
      const foundKey = objKeys.find(ok => ok.toLowerCase() === target);
      if (foundKey && obj[foundKey] !== undefined && obj[foundKey] !== null && obj[foundKey] !== "") return obj[foundKey] as string | number;
    }
    return "";
  };

  // Deduplicate roster data by unique_id before syncing to avoid chunk conflicts
  const uniqueRowsMap = new Map();
  rosterData.forEach((r) => {
    // Mapping keys based on user request and common variants
    const ma_nv = String(getVal(r, ["ma_nv", "ID Number", "employeeId", "ID", "Mã NV"])).trim();
    const ngay = String(getVal(r, ["ngay", "Date", "date", "Ngày"])).trim();
    const gio_vao = String(getVal(r, ["gio_vao", "From", "from", "Giờ vào", "Start"])).trim();
    const gio_ra = String(getVal(r, ["gio_ra", "To", "to", "Giờ ra", "End"])).trim();
    
    // Skip rows that lack essential identification
    if (!ma_nv || !ngay || !gio_vao) return;

    const unique_id = `${ma_nv}_${ngay}_${gio_vao}`;
    
    // Ensure all columns match the lowercase names in SQL
    uniqueRowsMap.set(unique_id, {
      l07: String(getVal(r, ["l07", "Center", "Trung tâm", "Cơ sở"])).trim(),
      business: String(getVal(r, ["business", "Business", "Khối", "Bộ phận", "BU"])).trim(),
      ma_nv,
      full_name: String(getVal(r, ["full_name", "Full Name", "Họ tên", "Name", "Họ và tên", "fullName"])).trim(),
      ngay,
      type: String(getVal(r, ["type", "Type", "Loại", "Task Type", "taskType"])).trim(),
      class: String(getVal(r, ["class", "Class", "Lớp", "Class Code", "classCode"])).trim(),
      gio_vao,
      gio_ra,
      duration: Number(getVal(r, ["duration", "Duration", "Số giờ", "Working Hours", "workingHours"])) || 0,
      notes: String(getVal(r, ["notes", "Notes", "Ghi chú"])).trim(),
      charge_to_center_mkt: String(getVal(r, ["chargeToCenterMkt", "charge_to_center_mkt", "Charge to Center MKT"])).trim(),
      unique_id
    });
  });

  const uniqueRows = Array.from(uniqueRowsMap.values());
  const actualTotal = uniqueRows.length;

  if (actualTotal === 0) {
    throw new Error("Không có dữ liệu hợp lệ (thiếu Mã NV, Ngày hoặc Giờ vào) để đồng bộ.");
  }

  for (let i = 0; i < actualTotal; i += chunkSize) {
    const chunk = uniqueRows.slice(i, i + chunkSize);
    
    let response;
    let retries = 3;
    while (retries > 0) {
      try {
        response = await supabase
          .from("roster_cham_cong")
          .upsert(chunk, { onConflict: 'unique_id' });
        
        if (response.error && (response.error.message.includes("fetch") || response.error.message.includes("Failed to fetch"))) {
          throw new Error(response.error.message);
        }
        break; // Success or non-network error
      } catch (err: unknown) {
        retries--;
        if (retries === 0) {
          if (err instanceof Error && (err.message.includes("fetch") || err.name === "TypeError")) {
            throw new Error("Không thể kết nối tới Supabase (Failed to fetch). Vui lòng kiểm tra lại URL Supabase trong phần Settings và đảm bảo Project của bạn đang hoạt động (không bị tạm dừng).");
          }
          throw err;
        }
        await new Promise(r => setTimeout(r, 1000)); // Wait 1s before retry
      }
    }

    const { error } = response!;

    if (error) {
      if (error.message.includes('relation "roster_cham_cong" does not exist')) {
        throw new Error("Bảng 'roster_cham_cong' chưa tồn tại trên Supabase. Vui lòng chạy script SQL setup trong phần cấu hình Supabase của bạn.");
      }
      
      if (error.message.includes("Failed to fetch") || error.message.includes("fetch")) {
        throw new Error("Không thể kết nối tới Supabase (Failed to fetch). Vui lòng kiểm tra lại URL Supabase trong phần Settings và đảm bảo Project của bạn đang hoạt động (không bị tạm dừng).");
      }

      // Provide detailed error info for RLS or column mismatch debugging
      const detail = error.details || error.hint || "";
      throw new Error(`Supabase Error [${error.code}]: ${error.message}${detail ? " - " + detail : ""}`);
    }

    successCount += chunk.length;
    onProgress(successCount, actualTotal);

    // Minor throttle - increased to be gentler on the network
    await new Promise((resolve) => setTimeout(resolve, 200));
  }

  return { successCount, totalRows: actualTotal };
}
